name: beluga-challenge

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'
  actions: 'read'

jobs:
  deploy:
    name: deploy infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/133370309179/locations/global/workloadIdentityPools/beluga-wif-pool/providers/beluga-wif-provider'
          service_account: 'beluga-coding-cr-sa@gcp-it-ls-beluga-drddev-yy.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.1

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Build Application
        run: ./gradlew build

      - name: Docker
        run: ./docker.sh

      - name: Terraform
        run: ./terraform/terraform.sh
